import React, { useState, useMemo } from 'react';
import {
  X,
  Search,
  Copy,
  Check,
  Plus,
  BookOpen,
  Code2,
  Sliders,
  CheckCircle2,
  AlertTriangle,
  Layers,
} from 'lucide-react';
import { useWorkflowStore } from '../../store/useWorkflowStore';

interface HelpModalProps {
  isOpen: boolean;
  onClose: () => void;
}

type TabType = 'connectors' | 'conditions' | 'templating' | 'validation';

interface ConnectorActionDoc {
  action: string;
  connector: 'http' | 'gitlab' | 'jira' | 'logger' | 'internal';
  title: string;
  description: string;
  requiredParams: string[];
  optionalParams: string[];
  sampleOutput: string;
  yamlSnippet: string;
}

const CONNECTOR_DOCS: ConnectorActionDoc[] = [
  // HTTP
  {
    action: 'http.get',
    connector: 'http',
    title: 'HTTP GET Request',
    description: 'Performs a GET request to an external HTTP/REST endpoint.',
    requiredParams: ['url'],
    optionalParams: ['headers', 'query', 'timeout'],
    sampleOutput: '{ status_code: 200, body: {...}, headers: {...} }',
    yamlSnippet: `- id: "fetch_api_data"
  action: "http.get"
  params:
    url: "https://api.example.com/v1/resource/{{ .trigger.payload.id }}"
    headers:
      Authorization: "Bearer {{ .vars.api_token }}"
    timeout: 10
  next_steps: []`,
  },
  {
    action: 'http.post',
    connector: 'http',
    title: 'HTTP POST Request',
    description: 'Sends a POST request with JSON or form payload.',
    requiredParams: ['url'],
    optionalParams: ['body', 'headers', 'query', 'timeout'],
    sampleOutput: '{ status_code: 201, body: {...}, headers: {...} }',
    yamlSnippet: `- id: "send_webhook_notification"
  action: "http.post"
  params:
    url: "https://hooks.slack.com/services/T00/B00/XXXX"
    headers:
      Content-Type: "application/json"
    body:
      text: "Merge Request #{{ .trigger.payload.object_attributes.iid }} opened by {{ .trigger.payload.user.username }}"
  next_steps: []`,
  },
  {
    action: 'http.put',
    connector: 'http',
    title: 'HTTP PUT Request',
    description: 'Sends a PUT request to update an existing remote resource.',
    requiredParams: ['url'],
    optionalParams: ['body', 'headers', 'query', 'timeout'],
    sampleOutput: '{ status_code: 200, body: {...} }',
    yamlSnippet: `- id: "update_remote_state"
  action: "http.put"
  params:
    url: "https://api.example.com/v1/items/{{ .steps.fetch_item.output.body.id }}"
    body:
      status: "processed"
  next_steps: []`,
  },
  {
    action: 'http.delete',
    connector: 'http',
    title: 'HTTP DELETE Request',
    description: 'Sends a DELETE request to remove a remote resource.',
    requiredParams: ['url'],
    optionalParams: ['headers', 'query', 'timeout'],
    sampleOutput: '{ status_code: 204 }',
    yamlSnippet: `- id: "cleanup_temporary_resource"
  action: "http.delete"
  params:
    url: "https://api.example.com/v1/temp/{{ .trigger.payload.build_id }}"
  next_steps: []`,
  },

  // GitLab
  {
    action: 'gitlab.create_mr',
    connector: 'gitlab',
    title: 'GitLab: Create Merge Request',
    description: 'Opens a new Merge Request on a GitLab project.',
    requiredParams: ['project_id', 'source_branch', 'target_branch', 'title'],
    optionalParams: ['description', 'token'],
    sampleOutput: '{ id: 12345, iid: 42, web_url: "https://gitlab.com/...", state: "opened" }',
    yamlSnippet: `- id: "create_promotion_mr"
  action: "gitlab.create_mr"
  params:
    project_id: "{{ .trigger.payload.project.id }}"
    source_branch: "{{ .trigger.payload.object_attributes.source_branch }}"
    target_branch: "staging"
    title: "Promote: {{ .trigger.payload.object_attributes.title }}"
    description: "Automated promotion MR generated by OwlFlow."
  next_steps: []`,
  },
  {
    action: 'gitlab.merge_mr',
    connector: 'gitlab',
    title: 'GitLab: Accept / Merge MR',
    description: 'Merges an open Merge Request.',
    requiredParams: ['project_id', 'merge_request_iid'],
    optionalParams: ['commit_message', 'should_remove_source_branch', 'token'],
    sampleOutput: '{ id: 12345, iid: 42, state: "merged" }',
    yamlSnippet: `- id: "auto_merge_approved_mr"
  action: "gitlab.merge_mr"
  params:
    project_id: "{{ .trigger.payload.project.id }}"
    merge_request_iid: "{{ .trigger.payload.object_attributes.iid }}"
    commit_message: "Auto-merged by OwlFlow verification pipeline"
    should_remove_source_branch: true
  next_steps: []`,
  },
  {
    action: 'gitlab.add_comment',
    connector: 'gitlab',
    title: 'GitLab: Add Note / Comment',
    description: 'Posts a discussion comment or note to an existing Merge Request.',
    requiredParams: ['project_id', 'merge_request_iid', 'body'],
    optionalParams: ['token'],
    sampleOutput: '{ id: 98765, body: "...", author: {...} }',
    yamlSnippet: `- id: "post_mr_feedback"
  action: "gitlab.add_comment"
  params:
    project_id: "{{ .trigger.payload.project.id }}"
    merge_request_iid: "{{ .trigger.payload.object_attributes.iid }}"
    body: ":warning: **Policy Check Failed**: Direct PRs to default branch are restricted."
  next_steps: []`,
  },
  {
    action: 'gitlab.get_mr',
    connector: 'gitlab',
    title: 'GitLab: Get MR Details',
    description: 'Retrieves current status, commits, and attributes for a Merge Request.',
    requiredParams: ['project_id', 'merge_request_iid'],
    optionalParams: ['token'],
    sampleOutput: '{ id: 12345, state: "opened", has_conflicts: false }',
    yamlSnippet: `- id: "fetch_mr_details"
  action: "gitlab.get_mr"
  params:
    project_id: "{{ .trigger.payload.project.id }}"
    merge_request_iid: "{{ .trigger.payload.object_attributes.iid }}"
  next_steps: []`,
  },

  // Jira
  {
    action: 'jira.create_issue',
    connector: 'jira',
    title: 'Jira: Create Issue',
    description: 'Creates a new ticket/issue in Jira Cloud REST v3.',
    requiredParams: ['project_key', 'summary', 'issue_type'],
    optionalParams: ['description', 'priority', 'labels', 'assignee_id'],
    sampleOutput: '{ key: "PROJ-101", id: "10001", self: "https://..." }',
    yamlSnippet: `- id: "create_tracking_ticket"
  action: "jira.create_issue"
  params:
    project_key: "DEVOPS"
    issue_type: "Task"
    summary: "Release Incident: {{ .trigger.payload.repository.name }}"
    description: "Triggered from alert payload: {{ .trigger.payload.details }}"
    labels: ["owlflow", "automated"]
  next_steps: []`,
  },
  {
    action: 'jira.transition_issue',
    connector: 'jira',
    title: 'Jira: Transition Issue Status',
    description: 'Moves a Jira ticket to a new workflow status (e.g. In Progress, Done, Closed).',
    requiredParams: ['issue_key', 'transition_name_or_id'],
    optionalParams: ['comment'],
    sampleOutput: '{ issue_key: "PROJ-101", status: "Done" }',
    yamlSnippet: `- id: "close_jira_ticket"
  action: "jira.transition_issue"
  params:
    issue_key: "{{ .steps.create_tracking_ticket.output.key }}"
    transition_name_or_id: "Done"
    comment: "Closed automatically upon workflow verification success."
  next_steps: []`,
  },
  {
    action: 'jira.add_comment',
    connector: 'jira',
    title: 'Jira: Add Issue Comment',
    description: 'Appends a comment to an existing Jira ticket.',
    requiredParams: ['issue_key', 'comment'],
    optionalParams: [],
    sampleOutput: '{ id: "10042", body: "..." }',
    yamlSnippet: `- id: "add_jira_update"
  action: "jira.add_comment"
  params:
    issue_key: "{{ .vars.jira_ticket }}"
    comment: "Deployment verification completed with status: {{ .steps.verify.output.status_code }}"
  next_steps: []`,
  },
  {
    action: 'jira.search',
    connector: 'jira',
    title: 'Jira: JQL Search',
    description: 'Executes a JQL search query to find matching Jira issues.',
    requiredParams: ['jql'],
    optionalParams: ['max_results', 'fields'],
    sampleOutput: '{ total: 3, issues: [{ key: "PROJ-1" }, ...] }',
    yamlSnippet: `- id: "find_open_incidents"
  action: "jira.search"
  params:
    jql: "project = DEVOPS AND status != Done ORDER BY created DESC"
    max_results: 10
  next_steps: []`,
  },

  // Logger
  {
    action: 'logger.info',
    connector: 'logger',
    title: 'Logger: Info Level',
    description: 'Emits a structured JSON log entry at INFO level.',
    requiredParams: ['message'],
    optionalParams: ['fields'],
    sampleOutput: 'null',
    yamlSnippet: `- id: "log_event_received"
  action: "logger.info"
  params:
    message: "Received event for branch {{ .trigger.payload.object_attributes.source_branch }}"
    fields:
      author: "{{ .trigger.payload.user.username }}"
      target: "{{ .trigger.payload.object_attributes.target_branch }}"
  next_steps: []`,
  },
  {
    action: 'logger.warn',
    connector: 'logger',
    title: 'Logger: Warn Level',
    description: 'Emits a structured JSON warning log entry.',
    requiredParams: ['message'],
    optionalParams: ['fields'],
    sampleOutput: 'null',
    yamlSnippet: `- id: "log_retry_warning"
  action: "logger.warn"
  params:
    message: "Target branch non-standard: {{ .trigger.payload.object_attributes.target_branch }}"
  next_steps: []`,
  },
  {
    action: 'logger.error',
    connector: 'logger',
    title: 'Logger: Error Level',
    description: 'Emits a structured error log entry for debugging and alerting.',
    requiredParams: ['message'],
    optionalParams: ['fields'],
    sampleOutput: 'null',
    yamlSnippet: `- id: "log_pipeline_error"
  action: "logger.error"
  params:
    message: "Pipeline verification failed with code {{ .steps.check.output.status_code }}"
  next_steps: []`,
  },

  // Internal Data Filters
  {
    action: 'internal.regexMatch',
    connector: 'internal',
    title: 'Internal: Regex Match',
    description: 'Tests if a string matches a regular expression pattern.',
    requiredParams: ['item', 'regex'],
    optionalParams: [],
    sampleOutput: '{ match: true }',
    yamlSnippet: `- id: "check_branch_regex"
  action: "internal.regexMatch"
  params:
    item: "{{ .trigger.payload.object_attributes.source_branch }}"
    regex: "(?i)^cr/pre-prod-\\\\d+$"
  next_steps:
    - step_id: "next_action"
      condition: "{{ .steps.check_branch_regex.output.match }} == true"`,
  },
  {
    action: 'internal.startsWith',
    connector: 'internal',
    title: 'Internal: Starts With Any Prefix',
    description: 'Checks if an item string begins with any prefix in the provided list.',
    requiredParams: ['item', 'list'],
    optionalParams: [],
    sampleOutput: '{ found: true }',
    yamlSnippet: `- id: "check_protected_prefix"
  action: "internal.startsWith"
  params:
    item: "{{ .trigger.payload.object_attributes.source_branch }}"
    list: ["feature/", "bugfix/", "hotfix/"]
  next_steps: []`,
  },
  {
    action: 'internal.contains',
    connector: 'internal',
    title: 'Internal: Array Contains Item',
    description: 'Checks if an exact string item exists within a list or JSON array.',
    requiredParams: ['item', 'list'],
    optionalParams: [],
    sampleOutput: '{ found: true }',
    yamlSnippet: `- id: "check_allowed_environment"
  action: "internal.contains"
  params:
    item: "{{ .vars.env }}"
    list: ["staging", "production", "pre-prod"]
  next_steps: []`,
  },
  {
    action: 'internal.parseJson',
    connector: 'internal',
    title: 'Internal: Parse JSON String',
    description: 'Parses a raw JSON string into a queryable object hierarchy.',
    requiredParams: ['data'],
    optionalParams: [],
    sampleOutput: '{ ...parsedJsonObject }',
    yamlSnippet: `- id: "parse_raw_payload"
  action: "internal.parseJson"
  params:
    data: "{{ .trigger.payload.raw_body }}"
  next_steps: []`,
  },
  {
    action: 'internal.getField',
    connector: 'internal',
    title: 'Internal: Extract Nested Field',
    description: 'Extracts a specific key or nested property from a data object.',
    requiredParams: ['data', 'field'],
    optionalParams: [],
    sampleOutput: 'extractedValue',
    yamlSnippet: `- id: "extract_commit_id"
  action: "internal.getField"
  params:
    data: "{{ .steps.fetch_item.output.body }}"
    field: "commit_hash"
  next_steps: []`,
  },
];

export const HelpModal: React.FC<HelpModalProps> = ({ isOpen, onClose }) => {
  const [activeTab, setActiveTab] = useState<TabType>('connectors');
  const [searchQuery, setSearchQuery] = useState('');
  const [copiedAction, setCopiedAction] = useState<string | null>(null);
  const [selectedConnector, setSelectedConnector] = useState<string>('all');

  const { rawYaml, setRawYaml } = useWorkflowStore();

  const filteredConnectors = useMemo(() => {
    return CONNECTOR_DOCS.filter((doc) => {
      const matchesConnector = selectedConnector === 'all' || doc.connector === selectedConnector;
      const q = searchQuery.toLowerCase().trim();
      if (!q) return matchesConnector;
      const matchesSearch =
        doc.action.toLowerCase().includes(q) ||
        doc.title.toLowerCase().includes(q) ||
        doc.description.toLowerCase().includes(q) ||
        doc.requiredParams.some((p) => p.toLowerCase().includes(q));
      return matchesConnector && matchesSearch;
    });
  }, [searchQuery, selectedConnector]);

  const handleCopySnippet = (snippet: string, actionId: string) => {
    navigator.clipboard.writeText(snippet);
    setCopiedAction(actionId);
    setTimeout(() => setCopiedAction(null), 2000);
  };

  const handleInsertSnippet = (snippet: string, actionId: string) => {
    let newYaml = rawYaml.trim();
    if (!newYaml) {
      newYaml = `id: "sample_workflow"
name: "My Workflow"
status: "active"
trigger:
  type: "webhook"
  config:
    path: "/webhook"
    initial_step: "step_1"
steps:
${snippet.replace(/id: ".*"/, 'id: "step_1"')}`;
    } else {
      // Append step to steps list
      newYaml = `${newYaml}\n\n${snippet}`;
    }
    setRawYaml(newYaml);
    setCopiedAction(actionId);
    setTimeout(() => setCopiedAction(null), 2000);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-in fade-in duration-150">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-5xl h-[88vh] max-h-[850px] shadow-2xl flex flex-col overflow-hidden text-slate-200">
        {/* Header */}
        <div className="h-16 px-6 border-b border-slate-800 flex items-center justify-between shrink-0 bg-slate-900/90">
          <div className="flex items-center gap-3">
            <div className="h-9 w-9 rounded-xl bg-gradient-to-tr from-sky-500 to-blue-600 flex items-center justify-center shadow-lg shadow-sky-500/20 ring-1 ring-white/10">
              <BookOpen className="h-5 w-5 text-white" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white flex items-center gap-2">
                <span>OwlFlow Studio Reference & Component Guide</span>
                <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-sky-500/10 text-sky-400 border border-sky-500/20">
                  Cheat Sheet
                </span>
              </h2>
              <p className="text-xs text-slate-400">
                Lookup supported connector actions, parameters, condition syntax, and Go template expressions.
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="h-12 px-6 border-b border-slate-800 bg-slate-900/60 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-1.5">
            <button
              onClick={() => setActiveTab('connectors')}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-semibold transition ${
                activeTab === 'connectors'
                  ? 'bg-sky-500/10 text-sky-400 border border-sky-500/20'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Layers className="h-3.5 w-3.5" />
              <span>Connectors & Actions</span>
            </button>

            <button
              onClick={() => setActiveTab('conditions')}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-semibold transition ${
                activeTab === 'conditions'
                  ? 'bg-sky-500/10 text-sky-400 border border-sky-500/20'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Sliders className="h-3.5 w-3.5" />
              <span>Conditions & Regex</span>
            </button>

            <button
              onClick={() => setActiveTab('templating')}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-semibold transition ${
                activeTab === 'templating'
                  ? 'bg-sky-500/10 text-sky-400 border border-sky-500/20'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Code2 className="h-3.5 w-3.5" />
              <span>Go Templating & Variables</span>
            </button>

            <button
              onClick={() => setActiveTab('validation')}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-semibold transition ${
                activeTab === 'validation'
                  ? 'bg-sky-500/10 text-sky-400 border border-sky-500/20'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <CheckCircle2 className="h-3.5 w-3.5" />
              <span>Validation & Troubleshooting</span>
            </button>
          </div>

          {activeTab === 'connectors' && (
            <div className="relative w-64">
              <input
                type="text"
                placeholder="Search connector or method..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full bg-slate-950/80 border border-slate-700/80 rounded-lg pl-8 pr-3 py-1 text-xs text-slate-200 focus:outline-none focus:ring-1 focus:ring-sky-500 placeholder:text-slate-500"
              />
              <Search className="h-3.5 w-3.5 text-slate-500 absolute left-2.5 top-2 pointer-events-none" />
            </div>
          )}
        </div>

        {/* Tab Content Body */}
        <div className="flex-1 overflow-y-auto p-6 bg-slate-950/40">
          {/* 1. Connectors & Actions Tab */}
          {activeTab === 'connectors' && (
            <div className="space-y-4">
              {/* Connector Filter Pill Bar */}
              <div className="flex items-center gap-1.5 pb-2">
                {['all', 'http', 'gitlab', 'jira', 'logger', 'internal'].map((c) => (
                  <button
                    key={c}
                    onClick={() => setSelectedConnector(c)}
                    className={`px-3 py-1 rounded-lg text-xs font-medium uppercase tracking-wider transition ${
                      selectedConnector === c
                        ? 'bg-slate-800 text-white border border-slate-700 shadow-sm'
                        : 'text-slate-400 hover:text-slate-200 bg-slate-900/50'
                    }`}
                  >
                    {c}
                  </button>
                ))}
              </div>

              {/* Cards Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {filteredConnectors.map((doc) => (
                  <div
                    key={doc.action}
                    className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 hover:border-slate-700 flex flex-col justify-between transition"
                  >
                    <div>
                      {/* Card Title & Badge */}
                      <div className="flex items-center justify-between mb-2">
                        <span className="font-mono text-xs font-bold text-sky-400">
                          {doc.action}
                        </span>
                        <span className="text-[10px] font-semibold uppercase px-2 py-0.5 rounded bg-slate-800 text-slate-300 border border-slate-700">
                          {doc.connector}
                        </span>
                      </div>

                      <h4 className="text-sm font-semibold text-white mb-1">{doc.title}</h4>
                      <p className="text-xs text-slate-400 mb-3 leading-relaxed">
                        {doc.description}
                      </p>

                      {/* Required / Optional Params */}
                      <div className="space-y-1.5 text-xs mb-3">
                        <div className="flex items-baseline gap-1.5 flex-wrap">
                          <span className="text-[11px] font-semibold text-slate-500">Required:</span>
                          {doc.requiredParams.length > 0 ? (
                            doc.requiredParams.map((p) => (
                              <span
                                key={p}
                                className="font-mono text-[11px] px-1.5 py-0.5 rounded bg-rose-500/10 text-rose-300 border border-rose-500/20"
                              >
                                {p}
                              </span>
                            ))
                          ) : (
                            <span className="text-slate-500 text-[11px]">None</span>
                          )}
                        </div>

                        {doc.optionalParams.length > 0 && (
                          <div className="flex items-baseline gap-1.5 flex-wrap">
                            <span className="text-[11px] font-semibold text-slate-500">Optional:</span>
                            {doc.optionalParams.map((p) => (
                              <span
                                key={p}
                                className="font-mono text-[11px] px-1.5 py-0.5 rounded bg-slate-800 text-slate-400 border border-slate-700"
                              >
                                {p}
                              </span>
                            ))}
                          </div>
                        )}
                      </div>

                      {/* Output Shape preview */}
                      <div className="mb-3">
                        <span className="text-[10px] uppercase font-semibold text-slate-500 tracking-wider block mb-1">
                          Output Return Shape (.output)
                        </span>
                        <pre className="font-mono text-[11px] p-2 rounded-lg bg-slate-950 text-emerald-400/90 border border-slate-800 overflow-x-auto">
                          {doc.sampleOutput}
                        </pre>
                      </div>
                    </div>

                    {/* Action Buttons */}
                    <div className="pt-3 border-t border-slate-800/80 flex items-center justify-end gap-2">
                      <button
                        onClick={() => handleCopySnippet(doc.yamlSnippet, doc.action)}
                        className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-medium text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-750 border border-slate-700 transition"
                      >
                        {copiedAction === doc.action ? (
                          <>
                            <Check className="h-3 w-3 text-emerald-400" />
                            <span className="text-emerald-400">Copied</span>
                          </>
                        ) : (
                          <>
                            <Copy className="h-3 w-3 text-slate-400" />
                            <span>Copy YAML</span>
                          </>
                        )}
                      </button>

                      <button
                        onClick={() => handleInsertSnippet(doc.yamlSnippet, doc.action)}
                        className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-bold text-white bg-sky-600 hover:bg-sky-500 transition shadow-sm"
                      >
                        <Plus className="h-3 w-3" />
                        <span>Insert into Editor</span>
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* 2. Conditions & Regex Tab */}
          {activeTab === 'conditions' && (
            <div className="space-y-6 max-w-4xl">
              <div>
                <h3 className="text-sm font-bold text-white mb-2 flex items-center gap-2">
                  <Sliders className="h-4 w-4 text-sky-400" />
                  <span>Condition Expressions (`condition: '...'`)</span>
                </h3>
                <p className="text-xs text-slate-400 leading-relaxed">
                  Transitions in `next_steps` define conditional step execution. Expressions support comparisons, string helpers, regular expressions, and logical chaining.
                </p>
              </div>

              {/* Supported Operators Table */}
              <div className="rounded-xl border border-slate-800 bg-slate-900/60 overflow-hidden">
                <table className="w-full text-left text-xs">
                  <thead className="bg-slate-900 border-b border-slate-800 text-slate-400 font-semibold uppercase text-[10px]">
                    <tr>
                      <th className="p-3">Operator / Function</th>
                      <th className="p-3">Syntax & Example</th>
                      <th className="p-3">Description</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-800 font-mono text-[11px]">
                    <tr>
                      <td className="p-3 font-bold text-sky-400">== / !=</td>
                      <td className="p-3 text-slate-300">
                        <code>{'{{ .steps.fetch.output.status_code }} == 200'}</code>
                      </td>
                      <td className="p-3 font-sans text-slate-400">Equality and inequality comparisons</td>
                    </tr>
                    <tr>
                      <td className="p-3 font-bold text-sky-400">&lt;, &lt;=, &gt;, &gt;=</td>
                      <td className="p-3 text-slate-300">
                        <code>{'{{ .steps.ping.output.duration_ms }} <= 500'}</code>
                      </td>
                      <td className="p-3 font-sans text-slate-400">Numeric relational comparisons</td>
                    </tr>
                    <tr>
                      <td className="p-3 font-bold text-sky-400">hasPrefix</td>
                      <td className="p-3 text-slate-300">
                        <code>{'hasPrefix {{ .trigger.payload.branch }} "feat/"'}</code>
                      </td>
                      <td className="p-3 font-sans text-slate-400">
                        Checks if string begins with prefix (`hasPrefix item prefix` or `hasPrefix(item, prefix)`)
                      </td>
                    </tr>
                    <tr>
                      <td className="p-3 font-bold text-sky-400">regexMatch / matches</td>
                      <td className="p-3 text-slate-300">
                        <code>{'regexMatch {{ .branch }} "/^cr\\/pre-prod-\\d+$/i"'}</code>
                      </td>
                      <td className="p-3 font-sans text-slate-400">
                        Tests if string matches regex. Supports JS literals (`/.../flags`) and RE2 (`(?i)...`)
                      </td>
                    </tr>
                    <tr>
                      <td className="p-3 font-bold text-sky-400">! (Negation)</td>
                      <td className="p-3 text-slate-300">
                        <code>{'!regexMatch {{ .branch }} "/^cr\\/pre-prod-\\d+$/i"'}</code>
                      </td>
                      <td className="p-3 font-sans text-slate-400">Inverts the boolean outcome of any sub-expression</td>
                    </tr>
                    <tr>
                      <td className="p-3 font-bold text-sky-400">&amp;&amp; / ||</td>
                      <td className="p-3 text-slate-300">
                        <code>{'{{ .vars.env }} == "prod" && {{ .output.status }} == 200'}</code>
                      </td>
                      <td className="p-3 font-sans text-slate-400">Logical AND / Logical OR multi-clause chaining</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              {/* Realistic Example Cards */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="p-4 rounded-xl bg-slate-900 border border-slate-800">
                  <h4 className="text-xs font-bold text-white mb-1.5 flex items-center gap-1.5">
                    <CheckCircle2 className="h-3.5 w-3.5 text-emerald-400" />
                    <span>Branch & Release Validation</span>
                  </h4>
                  <pre className="font-mono text-[11px] p-2.5 rounded-lg bg-slate-950 text-slate-300 border border-slate-800/80 leading-relaxed overflow-x-auto">
{`condition: '{{ .trigger.payload.target }} == "main" && !regexMatch {{ .trigger.payload.source }} "/^cr\\/pre-prod-\\d+$/i" && {{ .trigger.payload.source }} != "staging"'`}
                  </pre>
                </div>

                <div className="p-4 rounded-xl bg-slate-900 border border-slate-800">
                  <h4 className="text-xs font-bold text-white mb-1.5 flex items-center gap-1.5">
                    <CheckCircle2 className="h-3.5 w-3.5 text-emerald-400" />
                    <span>HTTP Status & Retry Bounds</span>
                  </h4>
                  <pre className="font-mono text-[11px] p-2.5 rounded-lg bg-slate-950 text-slate-300 border border-slate-800/80 leading-relaxed overflow-x-auto">
{`condition: '{{ .steps.health_check.output.status_code }} == 200 || ({{ .steps.health_check.output.retries }} >= 3 && {{ .vars.fallback_enabled }} == true)'`}
                  </pre>
                </div>
              </div>
            </div>
          )}

          {/* 3. Go Templating & Variables Tab */}
          {activeTab === 'templating' && (
            <div className="space-y-6 max-w-4xl">
              <div>
                <h3 className="text-sm font-bold text-white mb-2 flex items-center gap-2">
                  <Code2 className="h-4 w-4 text-sky-400" />
                  <span>Go Template Resolution & Hierarchy</span>
                </h3>
                <p className="text-xs text-slate-400 leading-relaxed">
                  Inside parameters and conditions, `{'{{ ... }}'}` blocks dynamically resolve data from the execution context.
                </p>
              </div>

              {/* Hierarchy Tree */}
              <div className="p-4 rounded-xl bg-slate-900/90 border border-slate-800">
                <span className="text-[10px] font-semibold uppercase text-slate-400 tracking-wider block mb-2">
                  Context Objects Hierarchy
                </span>
                <pre className="font-mono text-xs text-sky-300 leading-relaxed">
{`.
├── trigger
│   ├── payload          # Webhook request body object
│   ├── headers          # HTTP headers (e.g. {{ .trigger.headers.Authorization }})
│   ├── query            # URL query params
│   ├── time             # Trigger timestamp
│   └── timezone         # Configured timezone
├── steps
│   └── <step_id>
│       └── output       # Connector return object (e.g. {{ .steps.fetch.output.status_code }})
├── vars                 # Top-level workflow variables (e.g. {{ .vars.environment }})
└── parent               # Direct parent step output array`}
                </pre>
              </div>

              {/* Template Helpers */}
              <div>
                <h4 className="text-xs font-bold text-white mb-2">Built-in Template Functions</h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                  <div className="p-3 rounded-lg bg-slate-900 border border-slate-800">
                    <span className="font-mono text-sky-400 font-bold">toJson</span>
                    <p className="text-slate-400 text-[11px] mt-0.5">Serializes object/array to compact JSON string.</p>
                    <code className="text-[10px] font-mono text-slate-300 block mt-1">{'{{ toJson .trigger.payload }}'}</code>
                  </div>

                  <div className="p-3 rounded-lg bg-slate-900 border border-slate-800">
                    <span className="font-mono text-sky-400 font-bold">toPrettyJson</span>
                    <p className="text-slate-400 text-[11px] mt-0.5">Serializes object to indented formatted JSON.</p>
                    <code className="text-[10px] font-mono text-slate-300 block mt-1">{'{{ toPrettyJson .steps.data.output }}'}</code>
                  </div>

                  <div className="p-3 rounded-lg bg-slate-900 border border-slate-800">
                    <span className="font-mono text-sky-400 font-bold">first</span>
                    <p className="text-slate-400 text-[11px] mt-0.5">Returns the first item from a slice or array.</p>
                    <code className="text-[10px] font-mono text-slate-300 block mt-1">{'{{ first .trigger.payload.commits }}'}</code>
                  </div>

                  <div className="p-3 rounded-lg bg-slate-900 border border-slate-800">
                    <span className="font-mono text-sky-400 font-bold">index</span>
                    <p className="text-slate-400 text-[11px] mt-0.5">Retrieves an item from a map or array by key/index.</p>
                    <code className="text-[10px] font-mono text-slate-300 block mt-1">{'{{ index .trigger.headers "X-Custom" }}'}</code>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* 4. Validation & Troubleshooting Tab */}
          {activeTab === 'validation' && (
            <div className="space-y-6 max-w-4xl">
              <div>
                <h3 className="text-sm font-bold text-white mb-2 flex items-center gap-2">
                  <CheckCircle2 className="h-4 w-4 text-emerald-400" />
                  <span>Validation Rules & Diagnostics</span>
                </h3>
                <p className="text-xs text-slate-400 leading-relaxed">
                  OwlFlow validates workflow definitions in real-time. Here is a guide to common validation errors and how to fix them:
                </p>
              </div>

              <div className="space-y-3">
                <div className="p-4 rounded-xl bg-slate-900 border border-slate-800">
                  <div className="flex items-center gap-2 mb-1">
                    <AlertTriangle className="h-4 w-4 text-rose-400" />
                    <span className="text-xs font-bold text-white">Unknown action connector: 'xyz.action'</span>
                  </div>
                  <p className="text-xs text-slate-400 leading-relaxed">
                    Action must follow `&lt;connector&gt;.&lt;method&gt;` format using one of the 5 built-in connectors: `http.*`, `gitlab.*`, `jira.*`, `logger.*`, or `internal.*`.
                  </p>
                </div>

                <div className="p-4 rounded-xl bg-slate-900 border border-slate-800">
                  <div className="flex items-center gap-2 mb-1">
                    <AlertTriangle className="h-4 w-4 text-rose-400" />
                    <span className="text-xs font-bold text-white">Missing required parameter: 'url' / 'project_id'</span>
                  </div>
                  <p className="text-xs text-slate-400 leading-relaxed">
                    Check the Connectors tab in this guide to confirm all mandatory parameters are supplied under `params:`.
                  </p>
                </div>

                <div className="p-4 rounded-xl bg-slate-900 border border-slate-800">
                  <div className="flex items-center gap-2 mb-1">
                    <AlertTriangle className="h-4 w-4 text-rose-400" />
                    <span className="text-xs font-bold text-white">Next step target 'xyz' not found in steps list</span>
                  </div>
                  <p className="text-xs text-slate-400 leading-relaxed">
                    Every `step_id` referenced in a `next_steps` array must match an existing step's `id` in the workflow.
                  </p>
                </div>

                <div className="p-4 rounded-xl bg-slate-900 border border-slate-800">
                  <div className="flex items-center gap-2 mb-1">
                    <AlertTriangle className="h-4 w-4 text-amber-400" />
                    <span className="text-xs font-bold text-white">Initial step 'xyz' does not exist</span>
                  </div>
                  <p className="text-xs text-slate-400 leading-relaxed">
                    For `webhook` triggers, `trigger.config.initial_step` must specify the first root step to execute.
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
