name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  backend-ci:
    uses: divmora/.github/.github/workflows/go-ci.yml@main
    with:
      go-version: '1.26'

  ui-ci:
    uses: divmora/.github/.github/workflows/node-ci.yml@main
    with:
      package-manager: 'pnpm'
      node-version: '24'
      working-directory: 'ui'
      test-command: 'test'
      enable-build: true
      build-command: 'pnpm build'

  cfn-ci:
    uses: divmora/.github/.github/workflows/cfn-ci.yml@main
    with:
      template-directory: 'deploy/cloudformation'
